### Sync test player
# @name syncTestPlayer

PUT {{baseUrl}}/players/{{testPlayerUuid}}
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "name": "{{testPlayerName}}"
}

###

### Sync target player
# @name syncTargetPlayer

PUT {{baseUrl}}/players/{{testTargetUuid}}
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "name": "{{testTargetName}}"
}

###

### Get test player by UUID
# @name getTestPlayer

GET {{baseUrl}}/players/{{testPlayerUuid}}
Authorization: Bearer {{$auth.token("server")}}

###

### Get target player by UUID
# @name getTargetPlayer

GET {{baseUrl}}/players/{{testTargetUuid}}
Authorization: Bearer {{$auth.token("server")}}

###

### Find test player by current name
# @name findTestPlayerByName

GET {{baseUrl}}/players?name={{testPlayerName}}
Authorization: Bearer {{$auth.token("server")}}

###

### Get test player name history
# @name getTestPlayerNameHistory

GET {{baseUrl}}/players/{{testPlayerUuid}}/names
Authorization: Bearer {{$auth.token("server")}}

###

### Set Discord ID
# @name setDiscordId

PUT {{baseUrl}}/players/{{testPlayerUuid}}/discord
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "discordId": "{{testDiscordId}}"
}

###

### Remove Discord ID
# @name removeDiscordId

PUT {{baseUrl}}/players/{{testPlayerUuid}}/discord
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "discordId": null
}

###

### Sync assigned acceptance target
# @name syncAcceptAssignedTarget

PUT {{baseUrl}}/players/{{acceptAssignedTargetUuid}}
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "name": "AcceptAssigned"
}

###

### Sync automatic acceptance target
# @name syncAcceptAutoTarget

PUT {{baseUrl}}/players/{{acceptAutoTargetUuid}}
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "name": "AcceptAuto"
}

###

### Sync acceptance conflict target
# @name syncAcceptConflictTarget

PUT {{baseUrl}}/players/{{acceptConflictTargetUuid}}
Authorization: Bearer {{$auth.token("server")}}
Content-Type: application/json

{
  "name": "AcceptConflict"
}