### Create reason
# @name createReason

POST {{baseUrl}}/reasons
Authorization: Bearer {{actorToken}}
Content-Type: application/json

{
  "key": "HTTP_TEST_{{$random.uuid}}",
  "name": "HTTP Test Reason",
  "description": "Reason created by HTTP client integration flow"
}

> {%
    client.global.set("reasonId", response.body.id);
%}

###

### Get created reason
# @name getReason

GET {{baseUrl}}/reasons/{{reasonId}}
Authorization: Bearer {{$auth.token("server")}}

###

### Get all reasons
# @name getReasons

GET {{baseUrl}}/reasons
Authorization: Bearer {{$auth.token("server")}}

###

### Update created reason
# @name updateReason

PATCH {{baseUrl}}/reasons/{{reasonId}}
Authorization: Bearer {{actorToken}}
Content-Type: application/json

{
  "name": "Updated HTTP Test Reason",
  "description": "Updated by HTTP client integration flow",
  "enabled": true
}

###

### Disable created reason
# @name disableReason

PATCH {{baseUrl}}/reasons/{{reasonId}}
Authorization: Bearer {{actorToken}}
Content-Type: application/json

{
  "enabled": false
}

###

### Enable created reason
# @name enableReason

PATCH {{baseUrl}}/reasons/{{reasonId}}
Authorization: Bearer {{actorToken}}
Content-Type: application/json

{
  "enabled": true
}