[versions]
kotlin = "2.4.10"
resource-factory = "1.3.1"
run-server = "3.1.0"
velocity = "4.1.1-SNAPSHOT"

#-----------------------------------------------------------------------------------------------------------------------
[libraries]
# Minecraft
paper = { group = "io.papermc.paper", name = "paper-api", version = "26.2.build.+" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# Spring
spring-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-oauth2 = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }

# Database
postgresql = { module = "org.postgresql:postgresql" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Configuration
jackson-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }

# Testing
kotlin-junit5-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test" }
spring-jooq-test = { module = "org.springframework.boot:spring-boot-starter-jooq-test" }
spring-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
spring-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

#-----------------------------------------------------------------------------------------------------------------------
[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

# Minecraft Server
bukkitConvention = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resource-factory" }
velocityConvention = { id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resource-factory" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "run-server" }
runVelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-server" }

# Misc
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
dotenv = { id = "io.github.klahap.dotenv", version = "1.1.3" }

# Spring
spring-boot = { id = "org.springframework.boot", version = "4.2.0-SNAPSHOT" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version = "1.1.7" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version = "3.21.8" }