import ../players.http
import ../auth.http
import ../reasons.http
import ../cases.http
import ../reports.http

run #syncTestPlayer

###

run #syncTargetPlayer

###

run #createActorToken

###

run #createReason

###

run #createInvestigationCase

###

run #createReport

###

run #assignReportToCase

###

run #closeInvestigationCaseExpectingConflict

###

run #dismissInvestigationCaseExpectingConflict

###

run #closeAssignedReport

###

run #closeInvestigationCase

###

run #getClosedInvestigationCase