import ../players.http
import ../auth.http
import ../cases.http

run #syncTestPlayer
###
run #syncTargetPlayer
###
run #createActorToken
###
run #createCloseCase
###
run #closeCase
###
run #createDismissCase
###
run #dismissCase