import ../players.http

run #syncTestPlayer

###

run #syncNameConflictPlayer

###

run #syncDuplicateCurrentName

###

run #getNameConflictPlayerAfterConflict

###

run #findOriginalPlayerByCaseInsensitiveName