import ../players.http
import ../auth.http
import ../reasons.http
import ../cases.http
import ../punishments.http

run #syncTestPlayer

###

run #syncTargetPlayer

###

run #createActorToken

###

run #createReason

###

run #createInvestigationCase

###

run #issuePunishment

###

run #getIssuedPunishment