import ../players.http
import ../auth.http
import ../reasons.http
import ../reports.http

run #syncTestPlayer
###
run #syncTargetPlayer
###
run #createActorToken
###
run #createReason
###
run #createCloseReport
###
run #closeReport