spring.application.name           = naughtylist-backend
spring.datasource.url             = ${DB_URL}
spring.datasource.username        = ${DB_USERNAME}
spring.datasource.password        = ${DB_PASSWORD}

logging.level.org.jooq.Constants  = off

naughtylist.security.jwt.secret   = ${JWT_SIGNING_SECRET}
naughtylist.security.jwt.issuer   = naughtylist-backend
naughtylist.security.jwt.audience = naughtylist-api
naughtylist.security.jwt.ttl      = PT15M