spring.application.name           = naughtylist-backend
spring.datasource.url             = ${DB_URL}
spring.datasource.username        = ${DB_USERNAME}
spring.datasource.password        = ${DB_PASSWORD}

naughtylist.security.jwt.secret   = ${JWT_SIGNING_SECRET}
naughtylist.security.jwt.issuer   = naughtylist-backend
naughtylist.security.jwt.audience = naughtylist-api
nughtylist.security.jwt.ttl       = PT15M